import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export interface IApiResponse {
  objectIDs: number[];
  primaryImageSmall: string;
  artistDisplayName: string;
  culture: string;
  period: string;
  accessionYear: string;
}

// Create a base query using fetch
const baseQuery = fetchBaseQuery({
  baseUrl: "https://collectionapi.metmuseum.org/public/collection/v1",
});

// Create an instance of RTK-Query API
export const api = createApi({
  baseQuery,
  endpoints: (builder) => ({
    fetchMuseumObjects: builder.query<number[], string>({
      query: (keyword) => `search?q=${keyword}`,
    }),
    fetchMuseumInfo: builder.query<IApiResponse, number>({
      query: (id) => `objects/${id}`,
    }),
  }),
});

// Export hooks generated by RTK-Query
export const { useFetchMuseumObjectsQuery, useFetchMuseumInfoQuery } = api;
